/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorJugar;
import controlador.ControladorUnirseAMesa;
import controlador.VistaUnirseAMesa;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Crupier;
import modelo.Jugador;
import modelo.Mesa;
import modelo.MesaException;
import modelo.TipoApuesta;

/**
 *
 * @author agus
 */
public class UnirseAMesa extends javax.swing.JDialog implements VistaUnirseAMesa {

    private ControladorUnirseAMesa controlador;
    
    
    public UnirseAMesa(java.awt.Frame parent, boolean modal, Jugador j) {
        super(parent, modal);
        initComponents();
        controlador= new ControladorUnirseAMesa(this,j);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lMesas = new javax.swing.JList();
        bUnirse = new javax.swing.JButton();
        bLogOff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lMesas);

        bUnirse.setText("Unirse");
        bUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUnirseActionPerformed(evt);
            }
        });

        bLogOff.setText("Log off");
        bLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bUnirse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLogOff))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bUnirse)
                    .addComponent(bLogOff))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUnirseActionPerformed
        
       
        
        Mesa mesaSeleccionada = (Mesa)lMesas.getSelectedValue();
        if(mesaSeleccionada!=null){
            try {
                controlador.unirseAMesa(mesaSeleccionada);
                new Jugar(null,false, controlador.getJugador(), mesaSeleccionada).setVisible(true);
            }catch (MesaException ex) {
                error(ex.getMessage());
            }
        }else{
            error("Debe elegir una mesa");
        }
        
            
            
        
    }//GEN-LAST:event_bUnirseActionPerformed

    private void bLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogOffActionPerformed
        controlador.cerrarSesion();
        dispose();
    }//GEN-LAST:event_bLogOffActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogOff;
    private javax.swing.JButton bUnirse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lMesas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMesas(ArrayList<Mesa> mesas) {
        lMesas.setListData(mesas.toArray());
    }

    @Override
    public void error(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    



}
